// 分类图标映射：将分类 key/emoji/图标名统一映射到 Lucide 图标组件
import {
  Activity,
  AirVent,
  AlarmClock,
  AlertTriangle,
  Anchor,
  AppWindow,
  Apple,
  Archive,
  Armchair,
  Axe,
  Baby,
  Banana,
  Bandage,
  Banknote,
  BarChart3,
  Bath,
  Battery,
  Bed,
  BedDouble,
  Beef,
  Beer,
  Bell,
  Bike,
  Bird,
  Blinds,
  Bluetooth,
  Bone,
  Book,
  BookOpen,
  Bookmark,
  Box,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Bus,
  Cable,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Candy,
  Car,
  Carrot,
  Cast,
  Cat,
  ChefHat,
  Cherry,
  Circle,
  CircleDot,
  Citrus,
  Clipboard,
  Clock,
  Cloud,
  Cloudy,
  Coffee,
  Cog,
  Coins,
  Compass,
  Construction,
  Cookie,
  Cpu,
  CreditCard,
  Croissant,
  Crosshair,
  Crown,
  CupSoda,
  Database,
  Diamond,
  Disc,
  Dog,
  DollarSign,
  DoorOpen,
  Drill,
  Droplet,
  Droplets,
  Drumstick,
  Dumbbell,
  Egg,
  EggFried,
  Eraser,
  Euro,
  Eye,
  Fan,
  FileCheck,
  FileText,
  Files,
  Film,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  Flashlight,
  Flower2,
  Folder,
  Footprints,
  Fuel,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  GlassWater,
  Glasses,
  Globe,
  Grape,
  Hammer,
  HardDrive,
  HardHat,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hexagon,
  Highlighter,
  History,
  Home,
  Hourglass,
  IceCream,
  Image,
  Infinity,
  JapaneseYen,
  Key,
  Keyboard,
  Lamp,
  Laptop,
  Layers,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  LineChart,
  Lock,
  Magnet,
  Map,
  MapPin,
  Maximize,
  Medal,
  Mic,
  Microwave,
  Milk,
  Monitor,
  Moon,
  Mountain,
  MousePointer2,
  Music,
  Navigation,
  Newspaper,
  Notebook,
  Nut,
  Octagon,
  Package,
  PackageOpen,
  Palette,
  Paperclip,
  ParkingSquare,
  PartyPopper,
  PawPrint,
  Pen,
  PenTool,
  Pencil,
  Pentagon,
  Pickaxe,
  PieChart,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Podcast,
  Printer,
  QrCode,
  Radio,
  Receipt,
  Refrigerator,
  Rocket,
  Router,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Scale,
  Scan,
  ScanFace,
  Scissors,
  Scroll,
  Server,
  Settings,
  Shapes,
  Shield,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  Shovel,
  ShowerHead,
  Shrub,
  Siren,
  Smartphone,
  Smile,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  Speaker,
  SprayCan,
  Sprout,
  Square,
  Star,
  Stethoscope,
  StickyNote,
  Sun,
  Syringe,
  Tablet,
  Tablets,
  Tag,
  Tags,
  Target,
  Tent,
  Thermometer,
  ThumbsUp,
  Timer,
  ToyBrick,
  Train,
  Trash2,
  TreePine,
  Trees,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Unlock,
  Usb,
  Users,
  UtensilsCrossed,
  VenetianMask,
  Video,
  Wallet,
  Webcam,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Watch,
  Watch as WatchIcon
} from 'lucide-react'

export const CATEGORY_ICON_MAP = {

  // 默认内置分类
  electronic: Smartphone,
  food: UtensilsCrossed,
  beverage: Coffee,
  daily: Droplets,
  kitchen: ChefHat,
  cleaning: Sparkles,
  medical: Pill,
  stationery: Pencil,
  tools: Wrench,
  other: Package,
  all: LayoutGrid,
  default: Tag,

  // 电子产品
  electronics: Smartphone,
  phone: Smartphone,
  mobile: Smartphone,
  smartphone: Smartphone,
  laptop: Laptop,
  computer: Laptop,
  tablet: Tablet,
  headphone: Headphones,
  earphone: Headphones,
  audio: Headphones,
  camera: Camera,
  webcam: Webcam,
  television: Tv,
  tv: Tv,
  display: Monitor,
  monitor: Monitor,
  smartwatch: Watch,
  watch: WatchIcon,
  wearable: Watch,
  cpu: Cpu,
  hardware: Cpu,
  battery: Battery,
  charger: Plug,
  cable: Cable,
  keyboard: Keyboard,
  mouse: MousePointer2,
  game: Gamepad2,
  console: Gamepad2,
  printer: Printer,
  speaker: Speaker,
  router: Router,
  network: Router,
  wifi: Wifi,
  bluetooth: Bluetooth,
  usb: Usb,
  cast: Cast,

  // 食品饮料
  foods: UtensilsCrossed,
  drink: CupSoda,
  drinks: CupSoda,
  water: GlassWater,
  wine: Wine,
  alcohol: Wine,
  beer: Beer,
  milk: Milk,
  coffee: Coffee,
  tea: Coffee,
  snack: Cookie,
  cookies: Cookie,
  candy: Candy,
  icecream: IceCream,
  cake: Cake,
  croissant: Croissant,
  pizza: Pizza,
  sandwich: Sandwich,
  soup: Soup,
  cooking: ChefHat,
  kitchenware: Refrigerator,
  refrigerator: Refrigerator,
  microwave: Microwave,

  // 水果 / 蔬菜 / 肉类
  fruit: Apple,
  fruits: Apple,
  apple: Apple,
  banana: Banana,
  cherry: Cherry,
  citrus: Citrus,
  grape: Grape,
  vegetable: Carrot,
  vegetables: Carrot,
  salad: Salad,
  carrot: Carrot,
  meat: Beef,
  beef: Beef,
  pork: Beef,
  chicken: Drumstick,
  drumstick: Drumstick,
  seafood: Fish,
  fish: Fish,
  egg: Egg,
  eggs: EggFried,

  // 母婴 / 家庭
  baby: Baby,
  maternity: Baby,
  child: Baby,
  kids: Baby,
  family: Users,
  mother: HeartHandshake,
  milkpowder: Milk,
  diaper: Baby,

  // 日用品 / 个护 / 美妆
  dailyuse: Droplets,
  toiletries: Droplets,
  skincare: Droplet,
  makeup: Palette,
  beauty: Sparkles,
  perfume: SprayCan,
  cleaner: SprayCan,
  broom: Brush,
  bucket: Droplets,
  trash: Trash2,
  washing: Droplets,
  clothing: Shirt,
  clothes: Shirt,
  shoes: Footprints,
  bag: ShoppingBag,
  handbag: ShoppingBag,
  gift: Gift,
  glasses: Glasses,
  sunglasses: Glasses,

  // 医药健康
  medicine: Pill,
  drug: Pill,
  pills: Pill,
  tablets: Tablets,
  health: HeartPulse,
  heartbeat: HeartPulse,
  stethoscope: Stethoscope,
  thermometer: Thermometer,
  bandage: Bandage,
  syringe: Syringe,
  firstaid: Briefcase,
  hospital: Building2,
  fitness: Activity,
  dumbbell: Dumbbell,

  // 文具办公
  pen: Pen,
  pencil: Pencil,
  marker: Highlighter,
  highlighter: Highlighter,
  eraser: Eraser,
  ruler: Ruler,
  book: Book,
  notebook: Notebook,
  read: BookOpen,
  bookmark: Bookmark,
  scissors: Scissors,
  paperclip: Paperclip,
  note: StickyNote,
  sticky: StickyNote,
  clipboard: Clipboard,
  calculator: Calculator,
  office: Briefcase,
  briefcase: Briefcase,
  desk: Monitor,

  // 图书音像
  library: Library,
  newspaper: Newspaper,
  scroll: Scroll,
  document: FileText,
  filecheck: FileCheck,
  files: Files,
  folder: Folder,
  music: Music,
  microphone: Mic,
  mic: Mic,
  video: Video,
  movie: Film,
  film: Film,
  photo: Image,
  image: Image,
  cd: Disc,
  disc: Disc,
  podcast: Podcast,
  radio: Radio,

  // 工具五金 / 维修
  tool: Wrench,
  hammer: Hammer,
  screwdriver: Hammer,
  drill: Drill,
  axe: Axe,
  shovel: Shovel,
  pickaxe: Pickaxe,
  wrench: Wrench,
  cog: Cog,
  settings: Settings,
  repair: Wrench,
  maintenance: Construction,
  hardhat: HardHat,
  construction: Construction,
  nut: Nut,
  magnet: Magnet,

  // 家居 / 智能家居
  home: Home,
  house: Home,
  furniture: Sofa,
  sofa: Sofa,
  armchair: Armchair,
  chair: Armchair,
  bed: Bed,
  bedroom: BedDouble,
  bathroom: Bath,
  toilet: Bath,
  shower: ShowerHead,
  lamp: Lamp,
  light: Lightbulb,
  bulb: Lightbulb,
  fan: Fan,
  aircon: AirVent,
  heater: Flame,
  blanket: Bed,
  curtain: Blinds,
  door: DoorOpen,
  window: AppWindow,
  building: Building2,
  smart: Wifi,
  smarthome: Wifi,
  plug: Plug,
  socket: Plug,

  // 户外 / 运动 / 旅行
  outdoor: Mountain,
  mountain: Mountain,
  sport: Trophy,
  gym: Dumbbell,
  travel: Plane,
  flight: Plane,
  camping: TreePine,
  tent: Tent,
  garden: Flower2,
  plant: Leaf,
  car: Car,
  automobile: Car,
  bicycle: Bike,
  bike: Bike,
  bus: Bus,
  train: Train,
  truck: Truck,
  rocket: Rocket,
  ship: Ship,
  sailboat: Sailboat,
  globe: Globe,
  map: Map,
  compass: Compass,
  navigation: Navigation,
  flashlight: Flashlight,
  fishing: Fish,

  // 宠物用品
  pet: PawPrint,
  dog: Dog,
  cat: Cat,
  bird: Bird,
  bone: Bone,

  // 车载用品
  vehicle: Car,
  fuel: Fuel,
  gas: Fuel,
  gauge: Gauge,
  speedometer: Gauge,
  parking: ParkingSquare,
  tire: Circle,

  // 天气 / 季节
  sun: Sun,
  sunny: Sun,
  snow: Snowflake,
  rain: Umbrella,
  cloud: Cloud,
  cloudy: Cloudy,
  moon: Moon,
  night: Moon,
  wind: Wind,

  // 安全 / 消防
  key: Key,
  lock: Lock,
  unlock: Unlock,
  security: ShieldCheck,
  shield: Shield,
  protect: ShieldCheck,
  alarm: AlarmClock,
  bell: Bell,
  fire: Flame,
  siren: Siren,
  alert: AlertTriangle,
  warning: AlertTriangle,

  // 时间 / 提醒
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  alarmclock: AlarmClock,
  hourglass: Hourglass,
  history: History,

  // 爱好 / 收藏 / 乐器
  star: Star,
  heart: Heart,
  like: ThumbsUp,
  smile: Smile,
  instrument: Music,
  guitar: Music,
  piano: Music,
  art: Palette,
  paint: Brush,
  brush: Brush,
  design: PenTool,
  puzzle: Shapes,
  trophy: Trophy,
  medal: Medal,
  target: Target,
  flag: Flag,
  idea: Lightbulb,
  crown: Crown,
  gem: Gem,
  diamond: Diamond,
  jewelry: Gem,
  ring: Circle,

  // 玩具 / 派对
  toy: ToyBrick,
  toys: ToyBrick,
  gamepad: Gamepad2,
  blocks: ToyBrick,
  party: PartyPopper,
  birthday: Cake,
  balloon: Circle,
  celebration: PartyPopper,
  mask: VenetianMask,

  // 园艺
  leaf: Leaf,
  flower: Flower2,
  flowers: Flower2,
  tree: TreePine,
  trees: Trees,
  pine: TreePine,
  gardening: Shovel,
  sprout: Sprout,
  seed: Sprout,
  shrub: Shrub,
  grass: Wheat,

  // 财务
  money: Banknote,
  cash: Banknote,
  coin: Coins,
  card: CreditCard,
  creditcard: CreditCard,
  wallet: Wallet,
  receipt: Receipt,
  piggybank: PiggyBank,
  dollar: DollarSign,
  euro: Euro,
  yen: JapaneseYen,

  // 数据 / IT
  chart: BarChart3,
  barchart: BarChart3,
  piechart: PieChart,
  linechart: LineChart,
  activity: Activity,
  trending: TrendingUp,
  trendup: TrendingUp,
  layers: Layers,
  database: Database,
  storage: HardDrive,
  server: Server,
  bug: Bug,
  eye: Eye,
  scan: Scan,
  qrcode: QrCode,
  fingerprint: Fingerprint,
  scanface: ScanFace,

  // 测量 / 工具
  scale: Scale,
  crosshair: Crosshair,
  size: Maximize,

  // 通用容器 / 标签
  box: Box,
  archive: Archive,
  tag: Tag,
  tags: Tags,
  pin: MapPin,
  location: MapPin,
  package: Package,
  packageopen: PackageOpen,

  // 形状
  circle: CircleDot,
  square: Square,
  triangle: Triangle,
  hexagon: Hexagon,
  pentagon: Pentagon,
  octagon: Octagon,
  infinity: Infinity,
  anchor: Anchor,
}

// 图标候选池：新建分类时可从中循环挑选
export const CATEGORY_ICON_POOL = Object.entries(CATEGORY_ICON_MAP)
  .filter(([key]) => !['all', 'default'].includes(key))
  .map(([key, Icon]) => ({ key, Icon }))

export function getCategoryIcon(category) {
  if (!category) return CATEGORY_ICON_MAP.default
  const key = typeof category === 'string' ? category : category.key
  const icon = category?.icon
  // 如果分类存储的是 lucide 图标名，可直接映射
  if (icon && CATEGORY_ICON_MAP[icon]) return CATEGORY_ICON_MAP[icon]
  if (key && CATEGORY_ICON_MAP[key]) return CATEGORY_ICON_MAP[key]
  return CATEGORY_ICON_MAP.default
}

export function getCategoryIconKeyByIndex(index) {
  const pool = CATEGORY_ICON_POOL
  return pool[index % pool.length]?.key || 'tag'
}
