// ===== features/items =====
// 物品管理特性层：重导出 lib/api.js 中所有物品相关函数
// 调用方应从 features/items 导入，而非直接引用 lib/api.js

export {
  uid,
  fetchAllItems,
  searchItems,
  fetchByCategory,
  fetchByCategoryAndKeyword,
  fetchItemsPaged,
  fetchItemsTotal,
  fetchCategoryCounts,
  createItem,
  updateItem,
  adjustQuantity,
  deleteItem,
  bulkDeleteItems,
  bulkUpdateCategory,
  bulkPreview,
  bulkUpdateField,
  normalizeCategoryKey,
  CATEGORY_ALIASES,
  categoryDisplayName,
  fetchCategories,
  createCategory,
  updateCategory,
  deleteCategory,
  reorderCategories,
  mergeCategories,
  fetchLocations,
  createLocation,
  updateLocation,
  deleteLocation,
  buildLocationTree,
  locationPath,
  locationParts,
  fetchLocationItemCounts,
  exportJSON,
  exportCSV,
  exportSelectedJSON,
  exportExpiringReport,
  importJSON,
  rebuildCategories,
  rebuildLocations,
  saveFile,
  openFile,
  getSettings,
  setSettings,
  setDataDir,
  resetDataDir,
  pickFolder,
  generateItemNo,
  locationMatchesPath,
  buildLocationCounts,
  fetchStatistics
} from '../../lib/api'